# Generated by Django 3.1.1 on 2020-09-28 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=15)),
                ('currency', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('market', models.CharField(blank=True, default='', max_length=20)),
                ('retailer', models.CharField(max_length=20)),
                ('retailer_sku', models.CharField(blank=True, default='', max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('url_original', models.URLField()),
                ('product_hash', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('spider_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('currency', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('sku_id', models.BigIntegerField()),
                ('out_of_stock', models.BooleanField()),
                ('size', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_urls', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.product')),
            ],
        ),
    ]
