# Generated by Django 3.1.1 on 2020-10-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200828_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='color',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
